<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FileAccessPortal.Domain\FileAccessPortal.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>..\..\Artifact\bin\FileAccessPortal.Api\</BaseOutputPath>
    <BaseIntermediateOutputPath>..\..\Artifact\obj\FileAccessPortal.Api\</BaseIntermediateOutputPath>
  </PropertyGroup>

 <Target Name="CopyReactBuild" AfterTargets="Publish">
        <ItemGroup>
            <ReactFiles Include="$(MSBuildThisFileDirectory)..\..\Artifact\client\**" />
        </ItemGroup>
        <Copy SourceFiles="@(ReactFiles)" DestinationFiles="@(ReactFiles->'$(PublishDir)wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
    </Target>
</Project>
