//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from "axios"
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  CancelToken,
} from "axios"

export class Access_RequestsClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ""
  }

  /**
   * @return OK
   */
  createAccessRequest(
    body: CreateAccessRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests"
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCreateAccessRequest(_response)
      })
  }

  protected processCreateAccessRequest(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  getAccessRequests(
    page: number,
    pageSize: number,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests?"
    if (page === undefined || page === null)
      throw new globalThis.Error(
        "The parameter 'page' must be defined and cannot be null."
      )
    else url_ += "Page=" + encodeURIComponent("" + page) + "&"
    if (pageSize === undefined || pageSize === null)
      throw new globalThis.Error(
        "The parameter 'pageSize' must be defined and cannot be null."
      )
    else url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&"
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAccessRequests(_response)
      })
  }

  protected processGetAccessRequests(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  getAccessRequestDetails(
    accessReqId: number,
    viewerEmployeeId: number,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests/{accessReqId}?"
    if (accessReqId === undefined || accessReqId === null)
      throw new globalThis.Error("The parameter 'accessReqId' must be defined.")
    url_ = url_.replace("{accessReqId}", encodeURIComponent("" + accessReqId))
    if (viewerEmployeeId === undefined || viewerEmployeeId === null)
      throw new globalThis.Error(
        "The parameter 'viewerEmployeeId' must be defined and cannot be null."
      )
    else
      url_ +=
        "viewerEmployeeId=" + encodeURIComponent("" + viewerEmployeeId) + "&"
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAccessRequestDetails(_response)
      })
  }

  protected processGetAccessRequestDetails(
    response: AxiosResponse
  ): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  reviewAccessRequestByHod(
    accessReqId: number,
    body: ReviewByHodRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests/{accessReqId}/hod-review"
    if (accessReqId === undefined || accessReqId === null)
      throw new globalThis.Error("The parameter 'accessReqId' must be defined.")
    url_ = url_.replace("{accessReqId}", encodeURIComponent("" + accessReqId))
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processReviewAccessRequestByHod(_response)
      })
  }

  protected processReviewAccessRequestByHod(
    response: AxiosResponse
  ): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  reviewAccessRequestByIt(
    accessReqId: number,
    body: ReviewByItRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests/{accessReqId}/it-review"
    if (accessReqId === undefined || accessReqId === null)
      throw new globalThis.Error("The parameter 'accessReqId' must be defined.")
    url_ = url_.replace("{accessReqId}", encodeURIComponent("" + accessReqId))
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processReviewAccessRequestByIt(_response)
      })
  }

  protected processReviewAccessRequestByIt(
    response: AxiosResponse
  ): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  revokeAccessRequest(
    accessReqId: number,
    body: RevokeAccessRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests/{accessReqId}/revoke"
    if (accessReqId === undefined || accessReqId === null)
      throw new globalThis.Error("The parameter 'accessReqId' must be defined.")
    url_ = url_.replace("{accessReqId}", encodeURIComponent("" + accessReqId))
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRevokeAccessRequest(_response)
      })
  }

  protected processRevokeAccessRequest(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  renewAccessRequest(
    accessReqId: number,
    body: RenewAccessRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/access-requests/{accessReqId}/renew"
    if (accessReqId === undefined || accessReqId === null)
      throw new globalThis.Error("The parameter 'accessReqId' must be defined.")
    url_ = url_.replace("{accessReqId}", encodeURIComponent("" + accessReqId))
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRenewAccessRequest(_response)
      })
  }

  protected processRenewAccessRequest(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }
}

export class AuthClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ""
  }

  /**
   * @return OK
   */
  login(body: LoginRequest, cancelToken?: CancelToken): Promise<LoginResponse> {
    let url_ = this.baseUrl + "/api/auth/login"
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processLogin(_response)
      })
  }

  protected processLogin(response: AxiosResponse): Promise<LoginResponse> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<LoginResponse>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<LoginResponse>(null as any)
  }
}

export class DashboardClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ""
  }

  /**
   * @return OK
   */
  getDashboard(
    employeeId: number,
    page: number,
    pageSize: number,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/dashboard/{employeeId}?"
    if (employeeId === undefined || employeeId === null)
      throw new globalThis.Error("The parameter 'employeeId' must be defined.")
    url_ = url_.replace("{employeeId}", encodeURIComponent("" + employeeId))
    if (page === undefined || page === null)
      throw new globalThis.Error(
        "The parameter 'page' must be defined and cannot be null."
      )
    else url_ += "Page=" + encodeURIComponent("" + page) + "&"
    if (pageSize === undefined || pageSize === null)
      throw new globalThis.Error(
        "The parameter 'pageSize' must be defined and cannot be null."
      )
    else url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&"
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetDashboard(_response)
      })
  }

  protected processGetDashboard(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }
}

export class NotificationsClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ""
  }

  /**
   * @return OK
   */
  getNotifications(
    employeeId: number,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/notifications/{employeeId}"
    if (employeeId === undefined || employeeId === null)
      throw new globalThis.Error("The parameter 'employeeId' must be defined.")
    url_ = url_.replace("{employeeId}", encodeURIComponent("" + employeeId))
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetNotifications(_response)
      })
  }

  protected processGetNotifications(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  markNotificationRead(
    auditId: number,
    body: MarkNotificationReadRequest,
    cancelToken?: CancelToken
  ): Promise<Void> {
    let url_ = this.baseUrl + "/api/notifications/{auditId}/read"
    if (auditId === undefined || auditId === null)
      throw new globalThis.Error("The parameter 'auditId' must be defined.")
    url_ = url_.replace("{auditId}", encodeURIComponent("" + auditId))
    url_ = url_.replace(/[?&]$/, "")

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processMarkNotificationRead(_response)
      })
  }

  protected processMarkNotificationRead(
    response: AxiosResponse
  ): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }
}

export class UserClient {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ""
  }

  /**
   * @return OK
   */
  getAllUsers(cancelToken?: CancelToken): Promise<Void> {
    let url_ = this.baseUrl + "/api/User/GetAllUsers"
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetAllUsers(_response)
      })
  }

  protected processGetAllUsers(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }

  /**
   * @return OK
   */
  getUserById(employeeId: number, cancelToken?: CancelToken): Promise<Void> {
    let url_ = this.baseUrl + "/api/User/{employeeId}"
    if (employeeId === undefined || employeeId === null)
      throw new globalThis.Error("The parameter 'employeeId' must be defined.")
    url_ = url_.replace("{employeeId}", encodeURIComponent("" + employeeId))
    url_ = url_.replace(/[?&]$/, "")

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      cancelToken,
    }

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGetUserById(_response)
      })
  }

  protected processGetUserById(response: AxiosResponse): Promise<Void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = JSON.parse(resultData200)
      return Promise.resolve<Void>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers
      )
    }
    return Promise.resolve<Void>(null as any)
  }
}

export interface CreateAccessItemRequest {
  folderPath?: string | undefined
  accessType?: number
  reason?: string | undefined
}

export interface CreateAccessRequest {
  empId?: number
  reqTo?: number
  itsrNo?: string | undefined
  items?: CreateAccessItemRequest[] | undefined
}

export interface HodDto {
  employeeId?: number
  name?: string | undefined
  email?: string | undefined
}

export interface LoggedInUserDto {
  employeeId?: number
  name?: string | undefined
  email?: string | undefined
  departmentId?: number
  departmentName?: string | undefined
  role?: string | undefined
  departmentHod?: HodDto
}

export interface LoginRequest {
  employeeId?: number
  password?: string | undefined
}

export interface LoginResponse {
  session?: SessionDto
}

export interface MarkNotificationReadRequest {
  employeeId?: number
}

export interface RenewAccessRequest {
  requestedByEmployeeId?: number
  itsrNo?: string | undefined
}

export interface ReviewByHodRequest {
  reviewerEmployeeId?: number
  approved?: boolean
  comments?: string | undefined
}

export interface ReviewByItRequest {
  reviewerEmployeeId?: number
  approved?: boolean
  comments?: string | undefined
  itsrNo?: string | undefined
}

export interface RevokeAccessRequest {
  reviewerEmployeeId?: number
  comments?: string | undefined
}

export interface SessionDto {
  user?: LoggedInUserDto
}

export interface Void {}

export class SwaggerException extends Error {
  override message: string
  status: number
  response: string
  headers: { [key: string]: any }
  result: any

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super()

    this.message = message
    this.status = status
    this.response = response
    this.headers = headers
    this.result = result
  }

  protected isSwaggerException = true

  static isSwaggerException(obj: any): obj is SwaggerException {
    return obj.isSwaggerException === true
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): any {
  if (result !== null && result !== undefined) throw result
  else throw new SwaggerException(message, status, response, headers, null)
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true
}
