<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Database and Core Serialization">
    <PackageVersion Include="MySqlConnector" Version="2.5.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.16" />
    
    <!-- Central Versions for Entity Framework Core dependencies -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Label="Logging Engine">
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Label="API Documentation and Routing OpenApi">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.16" />
    <PackageVersion Include="Microsoft.OpenApi" Version="1.6.25" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>
</Project>
