<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <Compile Remove="Migrations\**" />
      <Content Remove="Migrations\**" />
      <EmbeddedResource Remove="Migrations\**" />
      <None Remove="Migrations\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="MySqlConnector" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="zb-client" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="ConnectionDll">
        <HintPath>Infrastructure\External Sources\ConnectionDll.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\AccessRequests\GetList\" />
    </ItemGroup>

    <Target Name="CopyReactBuild" AfterTargets="Publish">
        <ItemGroup>
            <ReactFiles Include="$(MSBuildThisFileDirectory)../Artifact/client/**" />
        </ItemGroup>
        <Copy SourceFiles="@(ReactFiles)" DestinationFiles="@(ReactFiles->'$(PublishDir)wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
    </Target>
    <ItemGroup>
        <Content Include="Infrastructure\Db\Folders.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup></Project>
