<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Remove="External Sources\**" />
    <Content Remove="External Sources\**" />
    <EmbeddedResource Remove="External Sources\**" />
    <None Remove="External Sources\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Oracle.EntityFrameworkCore" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="System.Data.OracleClient" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ConnectionDll">
      <HintPath>Infrastructure\Oracle\ConnectionDll.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyReactBuild" AfterTargets="Publish" Condition="Exists('$(MSBuildThisFileDirectory)../Artifact/client/index.html')">
    <ItemGroup>
      <ReactFiles Include="$(MSBuildThisFileDirectory)../Artifact/client/**" />
    </ItemGroup>
    <Copy SourceFiles="@(ReactFiles)" DestinationFiles="@(ReactFiles->'$(PublishDir)wwwroot/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

</Project>
