// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Db;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504065844_AddBudgetApprovalsAndAudits")]
    partial class AddBudgetApprovalsAndAudits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BudgetId");

                    b.HasIndex("ProjectNumber")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("jan_budgets", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetApprovalEntity", b =>
                {
                    b.Property<int>("BudgetApproveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("BudgetApproveId");

                    b.HasIndex("BudgetId");

                    b.ToTable("jan_budget_approvals", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("jan_budget_categories", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Actual")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Planned")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("jan_budget_items", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetReqAuditEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetApproveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("BudgetId");

                    b.ToTable("jan_budget_audits", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetTemplateEntity", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("TemplateId");

                    b.ToTable("jan_budget_templates", (string)null);

                    b.HasData(
                        new
                        {
                            TemplateId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Standard Product Development Template",
                            TemplateJson = "[\r\n          { \"category\": \"Product Design\", \"items\": [\"Benchmarking sample\", \"FEA Analysis\", \"CFD Analysis\", \"Design consultancy\", \"Others\"] },\r\n          { \"category\": \"Concept development\", \"items\": [\"Comp.devpt-Concept\", \"Machining components\", \"Plastic - Hand moulds\", \"Rubber moulds\", \"3D printing\", \"RPT\", \"MIM\", \"Jigs & fixtures\", \"Concept testing\"] },\r\n          { \"category\": \"Prototype development\", \"items\": [\"Machining components\", \"Plastic - Inj. moulds\", \"Aluminium - Die casting\", \"Investment casting\", \"Stamping tools\", \"Rubber moulds\", \"Jigs & fixtures\", \"Comp. mfg.\", \"Testing\"] },\r\n          { \"category\": \"Product testing\", \"items\": [\"Testing instruments\", \"Testing fixtures\", \"Certification\", \"Others\"] },\r\n          { \"category\": \"Capital equipments\", \"items\": [\"Testing equipments\", \"Special machines\", \"Others\"] },\r\n          { \"category\": \"Field validation\", \"items\": [\"Product development\"] }\r\n        ]"
                        });
                });

            modelBuilder.Entity("Server.Domain.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("emp_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dept_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_salt");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_role");

                    b.HasKey("EmployeeId");

                    b.ToTable("jan_employees", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.HasOne("Server.Domain.Entities.BudgetTemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetApprovalEntity", b =>
                {
                    b.HasOne("Server.Domain.Entities.Budget", "Budget")
                        .WithMany("Approvals")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("Server.Domain.Entities.Budget", "Budget")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetItem", b =>
                {
                    b.HasOne("Server.Domain.Entities.BudgetCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetReqAuditEntity", b =>
                {
                    b.HasOne("Server.Domain.Entities.Budget", "Budget")
                        .WithMany("Audits")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Audits");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
