// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Db;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415071034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Server.Domain.Entities.AccessApprovalEntity", b =>
                {
                    b.Property<int>("AccessApproveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessapprove_id");

                    b.Property<int>("AccessItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approval_status");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("comments");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.HasKey("AccessApproveId");

                    b.ToTable("jan_accessapproval", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessItemEntity", b =>
                {
                    b.Property<int>("AccessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("AccessType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_type");

                    b.Property<int>("ConfirmAccessType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirm_access_type");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("AccessItemId");

                    b.HasIndex("AccessReqId");

                    b.ToTable("jan_accessitems", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessReqAuditEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("audit_id");

                    b.Property<int?>("AccessApproveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessapprove_id");

                    b.Property<int?>("AccessItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<int>("RecipientEmpId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipient_emp_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_role");

                    b.HasKey("AuditId");

                    b.ToTable("jan_accessreqaudit", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Property<int>("AccessReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<int>("EmpId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emp_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAgreed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_agreed");

                    b.Property<string>("ItsrNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("itsr_no");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<int>("ReqTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_to");

                    b.HasKey("AccessReqId");

                    b.ToTable("jan_accessrequest", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("DeptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("HodEmail")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hod_email");

                    b.Property<int>("HodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hod_id");

                    b.Property<string>("HodName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("hod_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_salt");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedOn");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_role");

                    b.HasKey("EmployeeId");

                    b.ToTable("jan_portal_users", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessItemEntity", b =>
                {
                    b.HasOne("Server.Domain.Entities.AccessRequestEntity", null)
                        .WithMany("AccessItems")
                        .HasForeignKey("AccessReqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Navigation("AccessItems");
                });
#pragma warning restore 612, 618
        }
    }
}
