// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Db;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Server.Domain.Entities.AccessApprovalEntity", b =>
                {
                    b.Property<int>("AccessApproveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessapprove_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approval_status");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("comments");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.HasKey("AccessApproveId");

                    b.ToTable("jan_accessapproval", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessItemEntity", b =>
                {
                    b.Property<int>("AccessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("AccessType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_type");

                    b.Property<DateTime?>("AccessGrantedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_granted_on");

                    b.Property<DateTime?>("AccessValidUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_valid_until");

                    b.Property<int>("ConfirmAccessType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirm_access_type");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<string>("HodValidationComments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hod_validation_comments");

                    b.Property<int>("HodValidationStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hod_validation_status");

                    b.Property<bool>("IsHodValidated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_hod_validated");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("AccessItemId");

                    b.HasIndex("AccessReqId");

                    b.ToTable("jan_accessitems", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessReqAuditEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("audit_id");

                    b.Property<int?>("AccessApproveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessapprove_id");

                    b.Property<int?>("AccessItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<int>("RecipientEmpId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipient_emp_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_role");

                    b.HasKey("AuditId");

                    b.ToTable("jan_accessreqaudit", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Property<int>("AccessReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("AggregateStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aggregate_status");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<int>("EmpId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emp_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAgreed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_agreed");

                    b.Property<string>("ItsrNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("itsr_no");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_on");

                    b.Property<int>("ReqTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_to");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("AccessReqId");

                    b.ToTable("jan_accessrequest", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("emp_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dept_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_salt");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_role");

                    b.HasKey("EmployeeId");

                    b.ToTable("jan_employees", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessItemEntity", b =>
                {
                    b.HasOne("Server.Domain.Entities.AccessRequestEntity", null)
                        .WithMany("AccessItems")
                        .HasForeignKey("AccessReqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Navigation("AccessItems");
                });
#pragma warning restore 612, 618
        }
    }
}
