// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Server.Infrastructure.Db;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("BudgetId");

                    b.HasIndex("ProjectNumber")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("jan_budgets", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int?>("BudgetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("jan_budget_categories", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Actual")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("Planned")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("jan_budget_items", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetTemplateEntity", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.HasKey("TemplateId");

                    b.ToTable("jan_budget_templates", (string)null);

                    b.HasData(
                        new
                        {
                            TemplateId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Standard Product Development Template",
                            TemplateJson = "[\r\n          { \"category\": \"Product Design\", \"items\": [\"Benchmarking sample\", \"FEA Analysis\", \"CFD Analysis\", \"Design consultancy\", \"Others\"] },\r\n          { \"category\": \"Concept development\", \"items\": [\"Comp.devpt-Concept\", \"Machining components\", \"Plastic - Hand moulds\", \"Rubber moulds\", \"3D printing\", \"RPT\", \"MIM\", \"Jigs & fixtures\", \"Concept testing\"] },\r\n          { \"category\": \"Prototype development\", \"items\": [\"Machining components\", \"Plastic - Inj. moulds\", \"Aluminium - Die casting\", \"Investment casting\", \"Stamping tools\", \"Rubber moulds\", \"Jigs & fixtures\", \"Comp. mfg.\", \"Testing\"] },\r\n          { \"category\": \"Product testing\", \"items\": [\"Testing instruments\", \"Testing fixtures\", \"Certification\", \"Others\"] },\r\n          { \"category\": \"Capital equipments\", \"items\": [\"Testing equipments\", \"Special machines\", \"Others\"] },\r\n          { \"category\": \"Field validation\", \"items\": [\"Product development\"] }\r\n        ]"
                        });
                });

            modelBuilder.Entity("Server.Domain.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("emp_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("dept_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pwd_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pwd_salt");

                    b.Property<long>("Phone")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_role");

                    b.HasKey("EmployeeId");

                    b.ToTable("jan_employees", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.HasOne("Server.Domain.Entities.BudgetTemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("Server.Domain.Entities.Budget", "Budget")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetItem", b =>
                {
                    b.HasOne("Server.Domain.Entities.BudgetCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Server.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Server.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
