// <auto-generated />
using System;
using Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("CommittedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int>("Qty")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<int>("SNo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("JAN_PARTS");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Requisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CheckedBy")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("CheckedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("FromTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<decimal>("MonthlyQty")
                        .HasColumnType("NUMBER");

                    b.Property<string>("PageNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("PreparedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("PreparedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ProductRev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ProjectNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("RecNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<decimal>("Status")
                        .HasColumnType("NUMBER");

                    b.Property<string>("ToTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("JAN_REQUISITIONS");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<int>("Role")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("JAN_USERS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "admin@company.com",
                            EmployeeId = "1001",
                            FullName = "System Administrator",
                            Password = "password",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "hod@company.com",
                            EmployeeId = "1002",
                            FullName = "John HOD",
                            Password = "password",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Part", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Requisition", "Requisition")
                        .WithMany("Parts")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Requisition", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
